name: Build Flet Client

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        default: '1.0.0'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install uv (pip)
        run: pip install uv

      - name: Install deps
        run: uv pip install --system flet

      - name: Build macOS
        run: flet build macos --no-interactive

      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: build/macos

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install uv (pip)
        run: pip install uv

      - name: Install deps
        run: uv pip install --system flet

      - name: Build Windows
        run: flet build windows --no-interactive

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows